# Generated by Django 3.2.4 on 2021-06-11 22:51

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Постер')),
                ('title', models.CharField(max_length=60, verbose_name='Название фильма')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='Трейлер')),
                ('date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('genre', models.CharField(max_length=16, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('sum_tickets', models.IntegerField(default=0, verbose_name='Количество билетов к продаже')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='KinoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('urlMap', models.URLField(max_length=512, verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Местоположение кино',
                'verbose_name_plural': 'Местоположения кино',
            },
        ),
        migrations.CreateModel(
            name='PurchasedTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.BigIntegerField(default=0, verbose_name='Номер платежа')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_session', models.DateTimeField(verbose_name='Дата сеанса')),
                ('number_telephone', models.CharField(max_length=24, verbose_name='Номер телефона')),
                ('number_car', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('status', models.CharField(choices=[('none', 'none'), ('wait_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('not_valid', 'Недействителен')], default='none', max_length=32, verbose_name='Статус')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.films')),
            ],
            options={
                'verbose_name': 'Купленный билет',
                'verbose_name_plural': 'Купленные билеты',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kinolocation'),
        ),
    ]
