# Generated by Django 3.2.4 on 2021-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='status',
            field=models.CharField(choices=[('poster', 'В афише'), ('no_poster', 'Не в афише'), ('no_poster_system', 'Убран системой из афиши')], default='poster', max_length=32, verbose_name='Статус'),
        ),
    ]
